import { useFloodXStore } from '@/store'
import { Bell, AlertTriangle, Info } from 'lucide-react'

const SEV_STYLES: Record<string, string> = {
  EMERGENCY: 'alert-emergency', WARNING: 'alert-warning', WATCH: 'alert-watch', INFO: 'alert-info'
}

export default function AlertsPage() {
  const { alerts } = useFloodXStore()

  return (
    <div className="h-full overflow-y-auto p-4 space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-bold text-white flex items-center gap-2">
          <Bell size={20} className="text-accent-cyan" /> Alerts
        </h1>
        <span className="data-badge"><Info size={10} />DECISION SUPPORT ONLY — NOT OFFICIAL</span>
      </div>

      <div className="card bg-amber-500/5 border-amber-500/20 text-xs text-amber-400 flex items-start gap-2">
        <AlertTriangle size={14} className="flex-shrink-0 mt-0.5" />
        <span>These alerts are <strong>decision-support suggestions</strong> generated by FLOOD-X models. They are NOT official government emergency alerts or warnings.</span>
      </div>

      {alerts.length === 0 ? (
        <div className="card flex flex-col items-center justify-center py-16">
          <Bell size={40} className="text-slate-600 mb-3" />
          <p className="text-slate-500 text-sm">No active alerts</p>
          <p className="text-slate-600 text-xs mt-1">Start a simulation with heavy rainfall to generate alerts</p>
        </div>
      ) : (
        <div className="space-y-3">
          {['EMERGENCY', 'WARNING', 'WATCH', 'INFO'].map(sev => {
            const sAlerts = alerts.filter(a => a.severity === sev)
            if (!sAlerts.length) return null
            return (
              <div key={sev}>
                <p className="section-header">{sev} ({sAlerts.length})</p>
                <div className="space-y-2">
                  {sAlerts.map(alert => (
                    <div key={alert.alert_id} className={`rounded-lg p-4 ${SEV_STYLES[sev]}`}>
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex-1">
                          <p className="text-sm font-bold text-white">{alert.title}</p>
                          <p className="text-xs text-slate-300 mt-1">{alert.description}</p>
                          <div className="mt-2 p-2 rounded bg-surface-800 text-xs text-accent-cyan">
                            → {alert.recommended_action}
                          </div>
                        </div>
                        <div className="text-right text-xs text-slate-400 whitespace-nowrap">
                          <p>{Math.round(alert.confidence * 100)}% confidence</p>
                          <p className="mt-1 font-mono text-slate-600">{alert.alert_id}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
