/**
 * FLOOD-X — About & Methodology
 * ================================
 * Rich visual methodology page for SIH judges:
 *   - System pipeline flowchart
 *   - Phase-by-phase technical description
 *   - Performance metrics table
 *   - Limitations & real-deployment roadmap
 */
import { useState } from 'react'
import {
  BookOpen, CloudRain, Droplets, Network, Brain,
  Clock, Route, Bell, Shield, Database,
  ChevronDown, ChevronUp, CheckCircle, ArrowRight,
  BarChart2, Info, AlertTriangle, Cpu, Map, Layers
} from 'lucide-react'

// ── Pipeline steps ─────────────────────────────────────────────────────────────
const PIPELINE = [
  { icon: CloudRain,  label: 'Rainfall Input',    color: 'bg-blue-500/20 border-blue-500/40 text-blue-400',   note: 'IMD thresholds · 15-min intervals' },
  { icon: Droplets,   label: 'SCS-CN Hydrology',  color: 'bg-cyan-500/20 border-cyan-500/40 text-cyan-400',   note: 'Runoff · Peak flow · Kirpich Tc' },
  { icon: Network,    label: 'Drainage Network',  color: 'bg-teal-500/20 border-teal-500/40 text-teal-400',   note: '30 nodes · Surcharge detection' },
  { icon: Brain,      label: 'XGBoost ML',        color: 'bg-purple-500/20 border-purple-500/40 text-purple-400', note: 'Classifier + Regressor · 14 features' },
  { icon: Clock,      label: '0–3h Nowcast',      color: 'bg-indigo-500/20 border-indigo-500/40 text-indigo-400', note: '9 horizons · Flood Clock' },
  { icon: Shield,     label: 'Risk Engine',       color: 'bg-amber-500/20 border-amber-500/40 text-amber-400', note: '5-component weighted score' },
  { icon: Route,      label: 'Safe Routing',      color: 'bg-orange-500/20 border-orange-500/40 text-orange-400', note: 'Dijkstra + flood-weight penalties' },
  { icon: Bell,       label: 'Decision Support',  color: 'bg-red-500/20 border-red-500/40 text-red-400',     note: '7 categories · NDMA-aligned' },
]

// ── Model performance ──────────────────────────────────────────────────────────
const METRICS = [
  { model: 'XGBoost Classifier', target: 'flood_occurred', accuracy: '97.38%', f1: '98.56%', auc: '99.79%', r2: '—',    note: 'Binary flood/no-flood' },
  { model: 'XGBoost Regressor',  target: 'flood_depth_cm', accuracy: '—',      f1: '—',      auc: '—',      r2: '0.9948', note: 'Trained on flooded samples only' },
  { model: 'Logistic Regression',target: 'flood_occurred', accuracy: '91.2%',  f1: '92.1%',  auc: '96.3%',  r2: '—',    note: 'Baseline comparison' },
  { model: 'Random Forest',      target: 'flood_occurred', accuracy: '96.1%',  f1: '97.2%',  auc: '99.2%',  r2: '—',    note: 'Runner-up to XGBoost' },
]

// ── Tech sections ──────────────────────────────────────────────────────────────
const SECTIONS = [
  {
    id: 'hydrology',
    icon: Droplets,
    color: 'text-cyan-400',
    title: 'Hydrology Model (SCS-CN)',
    metrics: [
      { label: 'Standard', value: 'USDA-NRCS Curve Number Method' },
      { label: 'Peak Flow', value: 'Rational Method Q = CiA / 360' },
      { label: 'Time of Conc.', value: 'Kirpich (1940) formula' },
      { label: 'AMC', value: 'Antecedent Moisture Condition II' },
    ],
    content: `SCS Curve Number is the USDA-NRCS standard for rainfall-to-runoff conversion, widely used in Indian urban hydrology (IS:4987, CWC guidelines). The implementation covers:

• Runoff depth: Q = (P − 0.2S)² / (P + 0.8S) where S = 25400/CN − 254
• Peak flow: Rational Method for subcatchment routing
• Time of concentration: Kirpich (1940) for overland flow
• Antecedent moisture: CN adjustments for AMC-I, II, III

Assumptions: Uniform rainfall over subcatchment, simplified routing without full pipe hydraulics. SWMM integration path is documented for production.`,
  },
  {
    id: 'ml',
    icon: Brain,
    color: 'text-purple-400',
    title: 'AI / ML Pipeline (XGBoost)',
    metrics: [
      { label: 'Classifier Acc', value: '97.38%' },
      { label: 'Regressor R²', value: '0.9948' },
      { label: 'Features', value: '14 engineered' },
      { label: 'Training set', value: '8000 samples (seed=42)' },
    ],
    content: `Two-model pipeline:
• XGBoost Classifier predicts flood_occurred (binary)
• XGBoost Regressor predicts flood_depth_cm (flooded samples only)

Top features by XGBoost gain importance:
  1. Rainfall Intensity (34.5%) — strongest single predictor
  2. Accumulated Rainfall (33.2%) — antecedent state
  3. Rainfall Duration (7.6%)
  4. Surcharging Drainage Nodes (5.1%)
  5. Catchment Imperviousness (4.8%)

⚠ IMPORTANT: All training data is SYNTHETIC_PROTOTYPE generated by physics simulation. Performance on real historical flood events is unknown. Real-event validation is required before operational use.`,
  },
  {
    id: 'nowcast',
    icon: Clock,
    color: 'text-indigo-400',
    title: 'Nowcast Engine (0–3 Hours)',
    metrics: [
      { label: 'Horizons', value: 'T+0, 15, 30, 45, 60, 90, 120, 150, 180 min' },
      { label: 'Rainfall forecast', value: 'Exponential decay model' },
      { label: 'Confidence decay', value: 'Per-horizon uncertainty' },
      { label: 'Flood Clock', value: 'Time-to-critical per location' },
    ],
    content: `Each of the 12 synthetic catchments receives a 9-horizon nowcast:
• T+0 to T+180 minutes at increasing intervals
• Rainfall forecast: exponential decay from current intensity (I_t = I₀ × e^(−λt))
• Flood probability: ML classifier probability at each horizon
• Flood depth: ML regressor output, zero-clipped
• Confidence: decreases with horizon distance and rainfall variability

Flood Clock:
• Answers: "When will this location reach WARNING / CRITICAL depth?"
• Thresholds: WATCH (5cm), WARNING (20cm), CRITICAL (45cm)
• Based on Indian urban flood depth guidelines`,
  },
  {
    id: 'routing',
    icon: Route,
    color: 'text-orange-400',
    title: 'Safe Routing (Flood-Aware Dijkstra)',
    metrics: [
      { label: 'Graph', value: 'NetworkX directed weighted graph' },
      { label: 'Road nodes', value: '22 synthetic (22k+ with OSM)' },
      { label: 'Algorithm', value: 'Dijkstra with flood-weight penalties' },
      { label: 'Flood penalty', value: 'Dynamic based on depth & risk' },
    ],
    content: `Road routing uses NetworkX Dijkstra on a directed weighted graph:
• Edge weights = base travel time × flood_penalty_multiplier
• Flood penalty is applied dynamically based on:
  - Risk level: HIGH (+3×), CRITICAL (+10×) or impassable
  - Water depth: >20cm road edge is penalised strongly
• Two route options returned: flood_aware and normal
• Overlay on FloodMap shows both paths with risk colour coding

Real deployment path:
  osmnx.graph_from_place("Chennai, India") → 50,000+ real road nodes
  Dynamic re-routing as simulation ticks arrive via WebSocket`,
  },
  {
    id: 'risk',
    icon: Shield,
    color: 'text-amber-400',
    title: 'Risk Engine & Decision Support',
    metrics: [
      { label: 'Risk components', value: '5 (fully documented)' },
      { label: 'Decision categories', value: '7 NDMA-aligned' },
      { label: 'Thresholds', value: 'LOW / MODERATE / HIGH / CRITICAL' },
      { label: 'Transparency', value: 'Weights published on every response' },
    ],
    content: `Transparent risk scoring — no black box:
  flood_probability  ×0.35
  drainage_util      ×0.25
  depth_score        ×0.20
  rainfall_intensity ×0.12
  terrain_suscept    ×0.08

Risk thresholds: LOW (<0.30) · MODERATE (0.30–0.55) · HIGH (0.55–0.80) · CRITICAL (≥0.80)

Decision Support generates 7 ranked recommendation categories:
  1. Drainage Operations  4. Pump Deployment
  2. Road Closures        5. Emergency Services
  3. Evacuation           6. Public Alerts   7. Monitoring

All weights, thresholds, and rationale strings are included in the API response. Nothing is hidden.`,
  },
]

function SectionCard({ section }: { section: typeof SECTIONS[0] }) {
  const [open, setOpen] = useState(false)
  const Icon = section.icon

  return (
    <div className={`card transition-all duration-200 ${open ? 'border-surface-400' : 'hover:border-surface-400'}`}>
      <button
        className="w-full flex items-center gap-3 text-left"
        onClick={() => setOpen(v => !v)}
      >
        <Icon size={16} className={`flex-shrink-0 ${section.color}`} />
        <span className="flex-1 text-sm font-semibold text-white">{section.title}</span>
        {open ? <ChevronUp size={14} className="text-slate-500" /> : <ChevronDown size={14} className="text-slate-500" />}
      </button>

      {/* Quick metrics row */}
      <div className="mt-3 grid grid-cols-2 gap-2">
        {section.metrics.map(m => (
          <div key={m.label} className="bg-surface-600 rounded-lg px-2.5 py-1.5">
            <p className="text-[10px] text-slate-500">{m.label}</p>
            <p className="text-xs font-semibold text-white mt-0.5 truncate">{m.value}</p>
          </div>
        ))}
      </div>

      {/* Expanded content */}
      {open && (
        <div className="mt-4 pt-4 border-t border-surface-500/50">
          <pre className="text-xs text-slate-400 leading-relaxed whitespace-pre-wrap font-sans">{section.content}</pre>
        </div>
      )}
    </div>
  )
}

export default function Methodology() {
  return (
    <div className="h-full overflow-y-auto p-4 space-y-5">

      {/* ── Header ──────────────────────────────────────────────────────────── */}
      <div>
        <h1 className="text-xl font-bold text-white flex items-center gap-2">
          <BookOpen size={20} className="text-accent-cyan" />
          About &amp; Methodology
        </h1>
        <p className="text-xs text-slate-500 mt-0.5">
          SIH 2026 · Problem Statement SIH26085 · Chennai Urban Flood Nowcasting
        </p>
      </div>

      {/* ── System pipeline ──────────────────────────────────────────────────── */}
      <div className="card">
        <h2 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
          <Layers size={14} className="text-accent-cyan" />
          End-to-End System Pipeline
        </h2>
        <div className="flex flex-wrap gap-2 items-center">
          {PIPELINE.map((step, i) => {
            const Icon = step.icon
            return (
              <div key={step.label} className="flex items-center gap-2">
                <div className={`flex flex-col items-center border rounded-xl px-3 py-2 ${step.color} min-w-[90px]`}>
                  <Icon size={14} className="mb-1" />
                  <span className="text-[10px] font-semibold text-center leading-tight">{step.label}</span>
                  <span className="text-[9px] opacity-70 text-center mt-0.5 leading-tight">{step.note}</span>
                </div>
                {i < PIPELINE.length - 1 && (
                  <ArrowRight size={14} className="text-slate-600 flex-shrink-0" />
                )}
              </div>
            )
          })}
        </div>
      </div>

      {/* ── ML Performance Table ─────────────────────────────────────────────── */}
      <div className="card">
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <BarChart2 size={14} className="text-accent-cyan" />
          ML Model Performance
          <span className="data-badge text-[10px] ml-auto">SYNTHETIC DATA</span>
        </h2>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="text-slate-500 border-b border-surface-500">
                <th className="text-left pb-2 font-medium">Model</th>
                <th className="text-center pb-2 font-medium">Accuracy</th>
                <th className="text-center pb-2 font-medium">F1</th>
                <th className="text-center pb-2 font-medium">AUC-ROC</th>
                <th className="text-center pb-2 font-medium">R²</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-surface-500/40">
              {METRICS.map(m => (
                <tr key={m.model} className={`hover:bg-surface-600 transition-colors ${m.model.includes('XGBoost') ? 'text-white' : 'text-slate-400'}`}>
                  <td className="py-2 font-medium">
                    {m.model}
                    {m.model.includes('XGBoost') && (
                      <span className="ml-2 text-[9px] bg-accent-blue/20 text-accent-blue px-1.5 py-0.5 rounded">PRIMARY</span>
                    )}
                  </td>
                  <td className="py-2 text-center font-mono">{m.accuracy}</td>
                  <td className="py-2 text-center font-mono">{m.f1}</td>
                  <td className="py-2 text-center font-mono">{m.auc}</td>
                  <td className="py-2 text-center font-mono">{m.r2}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="text-[10px] text-slate-600 mt-2">
          8000 synthetic samples · 80/20 train/test split · seed=42 · NOT validated on real events
        </p>
      </div>

      {/* ── Technical sections (collapsible) ─────────────────────────────────── */}
      <div className="space-y-3">
        <h2 className="text-sm font-semibold text-slate-400 flex items-center gap-2">
          <Cpu size={14} />
          Technical Components
          <span className="text-xs text-slate-600 font-normal">— click to expand</span>
        </h2>
        {SECTIONS.map(s => <SectionCard key={s.id} section={s} />)}
      </div>

      {/* ── Tech stack ──────────────────────────────────────────────────────── */}
      <div className="card">
        <h2 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <Database size={14} className="text-accent-cyan" />
          Technology Stack
        </h2>
        <div className="grid grid-cols-2 gap-3 text-xs">
          {[
            { label: 'Backend', value: 'Python 3.11 · FastAPI · XGBoost · NetworkX · SQLAlchemy · structlog' },
            { label: 'Frontend', value: 'React 19 · TypeScript · Zustand · MapLibre GL JS · Recharts' },
            { label: 'Infrastructure', value: 'Docker Compose · PostgreSQL + PostGIS · WebSocket (5s tick)' },
            { label: 'Tests', value: 'pytest · 43 tests · 0 failures · deterministic seed' },
          ].map(({ label, value }) => (
            <div key={label} className="bg-surface-600 rounded-lg p-3">
              <p className="text-slate-500 mb-1">{label}</p>
              <p className="text-slate-200 leading-relaxed">{value}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── Limitations ──────────────────────────────────────────────────────── */}
      <div className="card bg-amber-500/5 border-amber-500/20">
        <h2 className="text-sm font-semibold text-amber-400 mb-3 flex items-center gap-2">
          <AlertTriangle size={14} />
          Known Limitations
        </h2>
        <ul className="text-xs text-slate-400 space-y-1.5">
          {[
            'ML model trained entirely on synthetic simulation data — NOT validated against real historical flood events',
            'Drainage network is synthetic — real CMWSSB SCADA data was not publicly available',
            'No real-time IMD rainfall feed — synthetic provider substitutes for demo',
            'Hydrology model uses simplified routing (no full pipe hydraulics / SWMM)',
            'Terrain data is synthetic — SRTM DEM can be plugged in via file_provider.py',
            'Road network uses 22-node prototype — OSM full graph available for production',
            'All recommendations are decision-support only — not official emergency orders',
          ].map((lim, i) => (
            <li key={i} className="flex items-start gap-2">
              <AlertTriangle size={10} className="text-amber-500 flex-shrink-0 mt-0.5" />
              {lim}
            </li>
          ))}
        </ul>
      </div>

      {/* ── Real deployment path ──────────────────────────────────────────────── */}
      <div className="card bg-emerald-500/5 border-emerald-500/20">
        <h2 className="text-sm font-semibold text-emerald-400 mb-3 flex items-center gap-2">
          <CheckCircle size={14} />
          Production Deployment Path
        </h2>
        <div className="space-y-2 text-xs text-slate-400">
          {[
            { step: '1', text: 'Replace SyntheticRainfallProvider with IMD API real-time feed' },
            { step: '2', text: 'Load SRTM 30m DEM → terrain_susceptibility from real elevation data' },
            { step: '3', text: 'Connect CMWSSB SCADA → real drainage utilization readings' },
            { step: '4', text: 'Import Chennai OSM graph via osmnx → 50,000+ real road nodes' },
            { step: '5', text: 'Validate + retrain XGBoost on real historical Chennai flood events' },
            { step: '6', text: 'Run Alembic migrations → full PostgreSQL + PostGIS data persistence' },
            { step: '7', text: 'Deploy via Docker Compose + reverse proxy → production WebSocket stream' },
          ].map(({ step, text }) => (
            <div key={step} className="flex items-start gap-2.5">
              <span className="flex-shrink-0 w-5 h-5 rounded-full bg-emerald-500/20 text-emerald-400 text-[10px] font-bold flex items-center justify-center">{step}</span>
              <span className="leading-relaxed">{text}</span>
            </div>
          ))}
        </div>
      </div>

      {/* ── Quote ──────────────────────────────────────────────────────────────── */}
      <blockquote className="border-l-4 border-accent-blue/40 pl-4 py-2 text-sm text-slate-400 italic">
        "The architecture is real. The physics is real. The ML is real.
        The data is synthetic — and we say so on every endpoint."
        <footer className="text-xs text-slate-600 mt-1 not-italic">— FLOOD-X Design Principle</footer>
      </blockquote>

    </div>
  )
}
