"""
FLOOD-X ML Training Pipeline
==============================
Trains XGBoost flood classifier and depth regressor on synthetic data.

DATA SOURCE: SYNTHETIC_PROTOTYPE — generated by services/ml/data_generator.py
MODELS: XGBoost Classifier (flood_occurred) + Regressor (flood_depth_cm)

Run from project root:
    python scripts/train_models.py

Output:
    models/xgboost_classifier_v1.json
    models/xgboost_regressor_v1.json
    models/scaler_v1.pkl
    models/training_metadata_v1.json

IMPORTANT: Model trained on synthetic data only.
Real-event validation required before operational deployment.
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

# Add backend to path
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "backend"))

import joblib
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    f1_score,
    mean_absolute_error,
    r2_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import xgboost as xgb

from app.services.ml.data_generator import generate_training_data, FEATURE_NAMES

MODELS_DIR = ROOT / "models"
MODELS_DIR.mkdir(exist_ok=True)

MODEL_VERSION = "v1"
RANDOM_STATE = 42


def main() -> None:
    print("=" * 60)
    print("FLOOD-X ML Training Pipeline")
    print("DATA: SYNTHETIC_PROTOTYPE (8000 samples, seed=42)")
    print("=" * 60)

    # ── 1. Generate training data ──────────────────────────────────────────────
    print("\n[1/6] Generating synthetic training data...")
    t0 = time.time()
    samples = generate_training_data(n_samples=8000, seed=RANDOM_STATE)
    print(f"      Generated {len(samples)} samples in {time.time()-t0:.1f}s")

    # Feature matrix
    X = np.array([s.to_feature_list() for s in samples])
    y_class = np.array([s.flood_occurred for s in samples])       # binary
    y_depth = np.array([s.flood_depth_cm for s in samples])       # continuous
    y_risk  = np.array([s.risk_level_int for s in samples])       # 0-3

    print(f"      Feature shape: {X.shape}")
    print(f"      Flood rate:     {y_class.mean()*100:.1f}%")
    print(f"      Depth range:    {y_depth.min():.1f} – {y_depth.max():.1f} cm")
    print(f"      Risk dist:      {dict(zip(*np.unique(y_risk, return_counts=True)))}")

    # ── 2. Train/test split ────────────────────────────────────────────────────
    print("\n[2/6] Splitting data (80% train / 20% test, stratified)...")
    X_train, X_test, yc_train, yc_test, yd_train, yd_test = train_test_split(
        X, y_class, y_depth,
        test_size=0.20,
        random_state=RANDOM_STATE,
        stratify=y_class,
    )
    print(f"      Train: {len(X_train)} | Test: {len(X_test)}")

    # ── 3. Feature scaling ─────────────────────────────────────────────────────
    print("\n[3/6] Fitting StandardScaler...")
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s  = scaler.transform(X_test)
    scaler_path = MODELS_DIR / f"scaler_{MODEL_VERSION}.pkl"
    joblib.dump(scaler, scaler_path)
    print(f"      Scaler saved: {scaler_path}")

    # ── 4. Train XGBoost Classifier ───────────────────────────────────────────
    print("\n[4/6] Training XGBoost Flood Classifier...")
    t0 = time.time()
    clf = xgb.XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=3,
        scale_pos_weight=((y_class == 0).sum() / (y_class == 1).sum()),
        use_label_encoder=False,
        eval_metric="logloss",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    clf.fit(
        X_train_s, yc_train,
        eval_set=[(X_test_s, yc_test)],
        verbose=False,
    )
    clf_train_time = time.time() - t0

    # Classifier evaluation
    yc_pred = clf.predict(X_test_s)
    yc_prob = clf.predict_proba(X_test_s)[:, 1]
    clf_acc   = accuracy_score(yc_test, yc_pred)
    clf_f1    = f1_score(yc_test, yc_pred, average="binary")
    clf_auc   = roc_auc_score(yc_test, yc_prob)

    print(f"      Trained in {clf_train_time:.1f}s")
    print(f"      Accuracy:  {clf_acc:.4f}")
    print(f"      F1:        {clf_f1:.4f}")
    print(f"      ROC-AUC:   {clf_auc:.4f}")
    print("\n      Classification Report:")
    print(classification_report(yc_test, yc_pred, target_names=["No Flood", "Flood"]))

    # Feature importances
    importances = dict(zip(FEATURE_NAMES, clf.feature_importances_.tolist()))
    top5 = sorted(importances.items(), key=lambda x: x[1], reverse=True)[:5]
    print("      Top-5 features:")
    for feat, imp in top5:
        print(f"        {feat}: {imp:.4f}")

    clf_path = MODELS_DIR / f"xgboost_classifier_{MODEL_VERSION}.json"
    clf.save_model(str(clf_path))
    print(f"      Classifier saved: {clf_path}")

    # ── 5. Train XGBoost Regressor ────────────────────────────────────────────
    print("\n[5/6] Training XGBoost Flood Depth Regressor...")
    t0 = time.time()
    # Only train on flooded samples (depth > 0) for better precision
    flooded_mask_train = yc_train == 1
    flooded_mask_test  = yc_test  == 1

    reg = xgb.XGBRegressor(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=3,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    if flooded_mask_train.sum() > 50:
        reg.fit(
            X_train_s[flooded_mask_train], yd_train[flooded_mask_train],
            eval_set=[(X_test_s[flooded_mask_test], yd_test[flooded_mask_test])],
            verbose=False,
        )
        reg_train_time = time.time() - t0

        yd_pred = reg.predict(X_test_s[flooded_mask_test])
        reg_mae = mean_absolute_error(yd_test[flooded_mask_test], yd_pred)
        reg_r2  = r2_score(yd_test[flooded_mask_test], yd_pred)
        print(f"      Trained in {reg_train_time:.1f}s (on {flooded_mask_train.sum()} flooded samples)")
        print(f"      MAE:  {reg_mae:.2f} cm")
        print(f"      R²:   {reg_r2:.4f}")
        reg_path = MODELS_DIR / f"xgboost_regressor_{MODEL_VERSION}.json"
        reg.save_model(str(reg_path))
        print(f"      Regressor saved: {reg_path}")
        reg_metrics = {"mae_cm": round(reg_mae, 3), "r2": round(reg_r2, 4)}
    else:
        print("      WARNING: Too few flooded samples to train regressor meaningfully")
        reg_path = None
        reg_metrics = {}

    # ── 6. Save training metadata ──────────────────────────────────────────────
    print("\n[6/6] Saving training metadata...")
    metadata = {
        "model_version": MODEL_VERSION,
        "trained_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "data_source": "SYNTHETIC_PROTOTYPE",
        "data_warning": "Model trained on synthetic data only. NOT validated against real Chennai flood events.",
        "n_samples": len(samples),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "features": FEATURE_NAMES,
        "n_features": len(FEATURE_NAMES),
        "train_test_split": 0.80,
        "random_state": RANDOM_STATE,
        "classifier": {
            "model": "XGBoostClassifier",
            "target": "flood_occurred",
            "n_estimators": 300,
            "accuracy": round(clf_acc, 4),
            "f1_score": round(clf_f1, 4),
            "roc_auc": round(clf_auc, 4),
            "feature_importances": importances,
            "file": str(clf_path),
        },
        "regressor": {
            "model": "XGBoostRegressor",
            "target": "flood_depth_cm",
            "n_estimators": 300,
            "n_flooded_train": int(flooded_mask_train.sum()),
            "metrics": reg_metrics,
            "file": str(reg_path) if reg_path else None,
        },
        "limitations": [
            "Trained entirely on SYNTHETIC_PROTOTYPE data",
            "Not validated against real historical flood events",
            "Performance on real data may differ significantly",
            "Suitable for prototype demonstration only",
            "Replace with real observational data for production deployment",
        ],
    }
    meta_path = MODELS_DIR / f"training_metadata_{MODEL_VERSION}.json"
    with open(meta_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"      Metadata saved: {meta_path}")

    print("\n" + "=" * 60)
    print("TRAINING COMPLETE")
    print(f"  Classifier — Accuracy: {clf_acc:.4f}  F1: {clf_f1:.4f}  AUC: {clf_auc:.4f}")
    if reg_metrics:
        print(f"  Regressor  — MAE: {reg_metrics['mae_cm']:.2f} cm  R²: {reg_metrics['r2']:.4f}")
    print(f"\nWARNING: Synthetic data only — not validated against real events")
    print(f"Models in: {MODELS_DIR}")
    print("=" * 60)


if __name__ == "__main__":
    main()
